# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: '4.0.4', pandoc-version: '2.11.4'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - name: Setup statsrv pandoc
        if: ${{ matrix.config.r == '4.0.4' }}
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: ${{ matrix.config.pandoc-version }}

      - name: Setup default pandoc
        if: ${{ matrix.config.r != '4.0.4' }}
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up tinytex
        uses: r-lib/actions/setup-tinytex@v2

      - name: Preinstall required latex packages
        run: >
          tlmgr install
          lastpage morefloats parskip pdflscape textpos multirow lipsum
          fancyhdr colortbl soul setspace relsize makecell threeparttable
          threeparttablex environ trimspaces

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install statsrv packages
        if: ${{ matrix.config.r == '4.0.4' }}
        run: |
          sudo apt install -y libx11-dev make libgit2-dev libssh2-1-dev libssl-dev zlib1g-dev libicu-dev libpng-dev libfontconfig1-dev libfreetype6-dev libfribidi-dev libharfbuzz-dev libxml2-dev libcurl4-openssl-dev
          R -q -e 'utils::install.packages("remotes")'
          R -q -e 'remotes::install_version("htmlTable", "2.4.1")'
          R -q -e 'remotes::install_version("scales", "1.3.0")'
          R -q -e 'remotes::install_version("Hmisc", "4.5-0")'
          R -q -e 'remotes::install_version("svglite", "2.1.3")'
          R -q -e 'remotes::install_github("FredHutch/VISCfunctions", dependencies = TRUE)'
          R -q -e 'utils::install.packages("rcmdcheck")'

      - uses: r-lib/actions/setup-r-dependencies@v2
        if: ${{ matrix.config.r != '4.0.4' }}
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
